const APFEL_API_URL = "http://localhost:11434/v1/chat/completions";
const APFEL_MODEL = "apple-foundationmodel";
const OPENAI_API_URL = "https://api.openai.com/v1/chat/completions";
const DEFAULT_LLM_SETTINGS = {
  provider: "apfel",
  openaiApiKey: "",
  openaiModel: "gpt-4.1-mini",
  ollamaHost: "",
  ollamaModel: ""
};
const DEFAULT_CHUNK_CFG = { latin: 10000, cjk: 2000, group: 3 };
const OPENAI_CONTEXT_TOKENS = 128000;
const chunkCfg = { ...DEFAULT_CHUNK_CFG };

const TEMPLATES = {
  summarise: {
    name: "Summarise",
    system:
      "Summarise the following text concisely using bullet points.\n\nAfter the summary, add a section '## AI Content Assessment' at the end that assesses whether the text was written by a human or generated by an AI. Consider stylistic cues such as formulaic phrasing, unnatural fluency, robotic repetition, generic or bland language, and text that reads like polished AI prose. Write 'AI Rating: X/5' exactly, where 1 means almost certainly written by a human and 5 means almost certainly AI-generated. Briefly justify the rating.",
    user: (text) => `Summarise this webpage:\n\n${text}`,
    combine:
      "Combine the following partial summaries into a single coherent overview. Use bullet points.\n\nAlso keep a final '## AI Content Assessment' section assessing whether the original text was written by AI. Write the overall AI likelihood rating exactly as 'AI Rating: X/5', where 1 means almost certainly human-written and 5 means almost certainly AI-generated, and briefly justify it."
  },
  key_points: {
    name: "Key Points",
    system:
      "Extract the most important key points from the text. List them as concise bullet points, grouped by theme.",
    user: (text) => `Extract key points from this webpage:\n\n${text}`,
    combine:
      "Merge and deduplicate the following key points into a single organized list grouped by theme."
  },
  explain_simply: {
    name: "Explain Simply",
    system:
      "Explain the content in simple terms that anyone can understand. Avoid jargon and technical language.",
    user: (text) => `Explain this webpage in simple terms:\n\n${text}`,
    combine:
      "Combine the following simplified explanations into a single easy-to-understand overview."
  },
  action_items: {
    name: "Action Items",
    system:
      "Extract actionable items, tasks, next steps, or recommendations from the text. List them clearly.",
    user: (text) => `Extract all action items from this webpage:\n\n${text}`,
    combine:
      "Combine and deduplicate the following action items into a single comprehensive list."
  },
  sermon_notes: {
    name: "Sermon Notes",
    system:
      "Generate sermon notes from the text. Include: main scripture references, key theological points, practical applications, and suggested sermon structure.",
    user: (text) => `Generate sermon notes from this webpage:\n\n${text}`,
    combine:
      "Combine the following sermon note segments into a single coherent set of sermon notes."
  },
  meeting_notes: {
    name: "Meeting Notes",
    system:
      "Generate structured meeting notes. Include: attendees, agenda items, discussion summary, decisions made, and action items with owners where identifiable.",
    user: (text) => `Generate meeting notes from this webpage:\n\n${text}`,
    combine:
      "Combine the following meeting note segments into a single structured set of meeting notes."
  },
  youtube_summary: {
    name: "YouTube Summary",
    system:
      "Summarise this YouTube video using its transcript and description.\n\nThe transcript lines are prefixed with [MM:SS] timestamps.\n\nOutput in this format:\n\n## Summary\nA concise overview of what the video covers.\n\n## Key Points\nConcise bullet points of the main takeaways. Start each bullet with the [MM:SS] timestamp where that point is covered in the video.\n\n## Usefulness Rating\nRate the usefulness of the video's content from 0 to 5, where 0 is useless and 5 is excellent. Penalise the rating if the video is unnecessarily padded out — for example, repetitive, slow-paced, drawn-out, or substantially longer than the actual content warrants. Write 'Rating: X/5' and briefly justify the rating, noting any padding.\n\n## AI Content Assessment\nAssess whether this video's transcript was written by a human or generated by an AI. Consider stylistic cues such as formulaic phrasing, unnatural fluency or rhythm, robotic repetition, generic or bland language, and text that reads more like polished prose than natural speech. Write 'AI Rating: X/5' exactly, where 1 means almost certainly written by a human and 5 means almost certainly AI-generated. Briefly justify your rating.",
    user: (text) => `Analyse this YouTube video:\n\n${text}`,
    combine:
      "Combine the following partial video analyses into one coherent summary with key points and a single final usefulness rating out of 5. Write the final rating exactly as 'Rating: X/5'. Keep the [MM:SS] timestamp at the start of each key point. When deciding the final rating, penalise videos that are unnecessarily padded out.\n\nAlso include a final '## AI Content Assessment' section assessing whether the video's transcript was written by a human or generated by an AI. Write the final AI likelihood rating exactly as 'AI Rating: X/5', where 1 means almost certainly human-written and 5 means almost certainly AI-generated, and briefly justify it."
  }
};

const SELECTION_TEMPLATES = {
  explain: {
    name: "Explain",
    system:
      "Explain the selected text clearly and in simple terms. Focus on what it means and why. Do not just restate the words.",
    user: (text) => `Explain this text:\n\n${text}`,
    combine: "Combine the following explanations into a single clear explanation."
  },
  summarize: {
    name: "Summarize",
    system:
      "Summarize the selected text concisely using bullet points.",
    user: (text) => `Summarize this text:\n\n${text}`,
    combine:
      "Combine the following partial summaries into a single coherent bullet-point summary."
  },
  rewrite: {
    name: "Rewrite",
    system:
      "Rewrite the selected text to improve clarity, flow, and readability. Preserve the original meaning, facts, and tone. Keep roughly the same length.",
    user: (text) => `Rewrite this text:\n\n${text}`,
    combine: "Combine the following rewritten segments into a single coherent rewrite."
  },
  critique: {
    name: "Critique",
    system:
      "Provide a balanced critique of the selected text. Note its strengths, weaknesses, logical issues, and concrete suggestions for improvement.",
    user: (text) => `Critique this text:\n\n${text}`,
    combine: "Combine the following critique segments into a single balanced critique."
  },
  translate: {
    name: "Translate",
    system: (text) =>
      `Translate the following text into ${translateTargetLang(text)}. Preserve the original meaning, tone, and formatting. Output only the translation, with no preamble.`,
    user: (text) => `Translate into ${translateTargetLang(text)}:\n\n${text}`,
    combine: "Combine the following translated segments into a single coherent translation."
  }
};

function translateTargetLang(text) {
  return detectLanguage(text) ? "English" : "Traditional Chinese";
}

function selectionLangInstruction(text, mode) {
  if (mode === "translate") return "";
  return detectLanguage(text) ? " Please write your entire response in Traditional Chinese." : "";
}

const PROCESSING_QUIPS = [
  "Summoning the text goblins...",
  "Feeding the server hamsters...",
  "Rearranging quantum particles...",
  "Polishing the crystal ball...",
  "Herding digital cats...",
  "Teaching a rock to think...",
  "Flipping datacenter light switches...",
  "Consulting the magic 8-ball...",
  "Stirring the algorithm pot...",
  "Brewing fresh tokens...",
  "Rotating bytes in the tumble dryer...",
  "Sharpening pencils for the AI...",
  "Inflating neural balloons...",
  "Warming up the word soup...",
  "Counting sheep to fall asleep...",
  "Tuning the imaginary ukulele...",
  "Chasing down runaway commas...",
  "Recruiting more thinking cells...",
  "Doing a rain dance on the keyboard...",
  "Watering the idea garden..."
];

function processingQuip() {
  return PROCESSING_QUIPS[Math.floor(Math.random() * PROCESSING_QUIPS.length)];
}

let isProcessing = false;
let llmSettings = { ...DEFAULT_LLM_SETTINGS };

const contexts = new Map();
let currentContext = null;
let currentTabId = null;

function makeContext(tab) {
  return {
    tabId: tab ? tab.id : 0,
    url: tab ? tab.url || "" : "",
    tabTitle: tab ? tab.title || "" : "",
    articleText: "",
    articleTitle: "",
    chatHistory: [],
    chatInitialized: false,
    resultSource: "",
    selectionNote: "",
    selectionMode: "",
    detectedLang: null,
    isYouTube: false,
    currentVideoId: "",
    transcript: "",
    transcriptError: "",
    transcriptOpen: false,
    templateValue: "summarise",
    panelTab: "process"
  };
}

function escapeHtml(text) {
  return text
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

function timeMarkLink(seconds, label) {
  const ctx = currentContext;
  if (!ctx || !ctx.currentVideoId) return label;
  const clean = label.replace(/^\[|\]$/g, "");
  return `<a class="time-link" href="#" data-seconds="${seconds}" title="Jump to ${clean}">${label}</a>`;
}

async function jumpToTime(seconds) {
  const ctx = currentContext;
  if (!ctx || !ctx.currentVideoId || !ctx.tabId) return;
  try {
    const resp = await chrome.tabs.sendMessage(ctx.tabId, { action: "seekTo", seconds });
    if (resp && resp.success) return;
  } catch {}
  const url = `https://www.youtube.com/watch?v=${ctx.currentVideoId}&t=${seconds}`;
  chrome.tabs.update(ctx.tabId, { url });
}

function ratingToStars(value) {
  const r = Math.max(0, Math.min(5, Number(value)));
  const pct = r * 20;
  return (
    `<span class="star-rating" title="Rating: ${r}/5">` +
    `<span class="star-bg">★★★★★</span>` +
    `<span class="star-fg" style="width:${pct}%">★★★★★</span>` +
    `</span> <strong>${r}/5</strong>`
  );
}

function aiRatingToHtml(value) {
  const r = Math.max(1, Math.min(5, Number(value)));
  const pct = r * 20;
  const label =
    r >= 4
      ? "Very likely AI"
      : r === 3
        ? "Possibly AI"
        : r === 2
          ? "Possibly human"
          : "Likely human";
  return (
    `<span class="robot-rating" title="AI likelihood: ${r}/5 (${label})">` +
    `<span class="robot-bg">🤖🤖🤖🤖🤖</span>` +
    `<span class="robot-fg" style="width:${pct}%">🤖🤖🤖🤖🤖</span>` +
    `</span> <strong>${r}/5</strong> <span class="ai-label">${label}</span>`
  );
}

function inlineFormat(text, aiRatings) {
  return text
    .replace(/\bAI\s*[-–—]?\s*Rating\s*:?\s*([0-4](?:\.[0-9]+)?|5(?:\.0+)?)\s*\/\s*5\b/gi, (m, v) => {
      if (aiRatings) {
        const idx = aiRatings.length;
        aiRatings.push(Number(v));
        return `AI_RATE_${idx}`;
      }
      return aiRatingToHtml(Number(v));
    })
    .replace(/`([^`]+)`/g, "<code>$1</code>")
    .replace(/\*\*\*(.+?)\*\*\*/g, "<strong><em>$1</em></strong>")
    .replace(/\*\*(.+?)\*\*/g, "<strong>$1</strong>")
    .replace(/\*(.+?)\*/g, "<em>$1</em>")
    .replace(/\[([^\]]+)\]\(([^)]+)\)/g, '<a href="$2" target="_blank" rel="noopener">$1</a>')
    .replace(/\[(\d{1,2}):(\d{1,2}):(\d{2})\]/g, (m, h, mm, ss) =>
      timeMarkLink(Number(h) * 3600 + Number(mm) * 60 + Number(ss), m)
    )
    .replace(/\[(\d{1,2}):(\d{2})\]/g, (m, mm, ss) =>
      timeMarkLink(Number(mm) * 60 + Number(ss), m)
    )
    .replace(/\((\d{1,2}):(\d{1,2}):(\d{2})\)/g, (m, h, mm, ss) =>
      timeMarkLink(Number(h) * 3600 + Number(mm) * 60 + Number(ss), `[${h}:${mm}:${ss}]`)
    )
    .replace(/\((\d{1,2}):(\d{2})\)/g, (m, mm, ss) =>
      timeMarkLink(Number(mm) * 60 + Number(ss), `[${mm}:${ss}]`)
    )
    .replace(/\b(?:Rating:\s*)?([0-4](?:\.[0-9]+)?|5(?:\.0+)?)\s*\/\s*5\b/gi, (m, v) => ratingToStars(Number(v)));
}

function renderMarkdown(text) {
  const escaped = escapeHtml(text);
  const aiRatings = [];
  const blocks = escaped.split(/\n\n+/).flatMap((raw) => {
    if (raw.trimStart().startsWith("```")) return [raw];
    const parts = [];
    let lines = [];
    for (const line of raw.split("\n")) {
      if (/^#{1,6}\s+/.test(line)) {
        if (lines.length) parts.push(lines.join("\n"));
        parts.push(line);
        lines = [];
      } else {
        lines.push(line);
      }
    }
    if (lines.length) parts.push(lines.join("\n"));
    return parts;
  });
  const out = [];
  let inList = false;
  let listTag = null;

  for (const raw of blocks) {
    const block = raw.trim();
    if (!block) continue;

    if (block.startsWith("```")) {
      closeList(out, inList, listTag);
      inList = false;
      const code = block.replace(/^```\w*\n?/, "").replace(/```$/, "");
      out.push(`<pre><code>${code}</code></pre>`);
      continue;
    }

    const hMatch = block.match(/^(#{1,6})\s+(.*)/);
    if (hMatch) {
      closeList(out, inList, listTag);
      inList = false;
      out.push(`<h${hMatch[1].length}>${inlineFormat(hMatch[2], aiRatings)}</h${hMatch[1].length}>`);
      continue;
    }

    const ratingMatch = block.match(/^\*{0,2}\s*Rating:\s*([0-9](?:\.[0-9])?)\s*\/\s*5\s*\*{0,2}$/i);
    if (ratingMatch) {
      closeList(out, inList, listTag);
      inList = false;
      out.push(`<p>${ratingToStars(Number(ratingMatch[1]))}</p>`);
      continue;
    }

    if (/^[-*_]{3,}$/.test(block)) {
      closeList(out, inList, listTag);
      inList = false;
      out.push("<hr>");
      continue;
    }

    if (/^(\s*)[-*]\s/.test(block)) {
      if (!inList || listTag !== "ul") {
        closeList(out, inList, listTag);
        out.push("<ul>");
        inList = true;
        listTag = "ul";
      }
      for (const line of block.split("\n")) {
        const m = line.match(/^(\s*)[-*]\s+(.*)/);
        if (m) out.push(`<li>${inlineFormat(m[2], aiRatings)}</li>`);
      }
      continue;
    }

    if (/^\d+\.\s/.test(block)) {
      if (!inList || listTag !== "ol") {
        closeList(out, inList, listTag);
        out.push("<ol>");
        inList = true;
        listTag = "ol";
      }
      for (const line of block.split("\n")) {
        const m = line.match(/^\d+\.\s+(.*)/);
        if (m) out.push(`<li>${inlineFormat(m[1], aiRatings)}</li>`);
      }
      continue;
    }

    closeList(out, inList, listTag);
    inList = false;
    const lines = block.split("\n");
    out.push(`<p>${lines.map((l) => inlineFormat(l, aiRatings)).join("<br>")}</p>`);
  }

  closeList(out, inList, listTag);
  return out
    .join("\n")
    .replace(/AI_RATE_(\d+)/g, (m, idx) => aiRatingToHtml(aiRatings[Number(idx)] ?? 1));
}

function closeList(out, inList, tag) {
  if (inList) out.push(tag === "ul" ? "</ul>" : "</ol>");
}

const $ = (id) => document.getElementById(id);

const tabBtns = document.querySelectorAll(".tab");
const processControls = $("controls");
const outputArea = $("output-area");
const chatArea = $("chat-area");
const templateSelect = $("template-select");
const processBtn = $("process-btn");
const statusEl = $("status");
const resultEl = $("result");
const copyBtn = $("copy-btn");
const pageTitleEl = $("page-title");
const tokenEstimateEl = $("token-estimate");
const transcriptRow = $("transcript-row");
const transcriptToggle = $("transcript-toggle");
const transcriptCopy = $("transcript-copy");
const transcriptEl = $("transcript");
const chatMessages = $("chat-messages");
const chatInput = $("chat-input");
const chatSend = $("chat-send");
const settingsBtn = $("settings-btn");
const settingsPanel = $("settings-panel");
const providerSelect = $("provider-select");
const openaiSettings = $("openai-settings");
const openaiApiKey = $("openai-api-key");
const openaiModel = $("openai-model");
const ollamaSettings = $("ollama-settings");
const ollamaHost = $("ollama-host");
const ollamaModel = $("ollama-model");
const ollamaRefresh = $("ollama-refresh");
const settingsSave = $("settings-save");
const settingsStatus = $("settings-status");

function updateProviderFields() {
  openaiSettings.classList.toggle("hidden", providerSelect.value !== "openai");
  ollamaSettings.classList.toggle("hidden", providerSelect.value !== "ollama");
}

function parseOllamaHost(value) {
  let url;
  try {
    url = new URL(value);
  } catch {
    throw new Error("Enter the Ollama host as http://host:port.");
  }
  if (!/^https?:$/.test(url.protocol) || !url.hostname || !url.port || url.username || url.password || url.pathname !== "/" || url.search || url.hash) {
    throw new Error("Enter the Ollama host as http://host:port.");
  }
  return url.origin;
}

async function loadOllamaModels(selectedModel = "") {
  const host = parseOllamaHost(ollamaHost.value.trim());
  ollamaHost.value = host;
  ollamaRefresh.disabled = true;
  ollamaModel.disabled = true;
  settingsStatus.textContent = "Loading available Ollama models...";
  try {
    const response = await fetch(`${host}/api/tags`);
    if (!response.ok) throw new Error(`Ollama returned HTTP ${response.status}.`);
    const data = await response.json();
    const models = [...new Set((data.models || []).map((model) => model.name || model.model).filter(Boolean))];
    ollamaModel.replaceChildren();
    if (!models.length) {
      ollamaModel.add(new Option("No installed models found", ""));
      settingsStatus.textContent = "No installed models found. Install one with ollama pull, then reload.";
      return false;
    }
    for (const model of models) ollamaModel.add(new Option(model, model));
    ollamaModel.value = models.includes(selectedModel) ? selectedModel : models[0];
    ollamaModel.disabled = false;
    settingsStatus.textContent = `${models.length} available Ollama model${models.length === 1 ? "" : "s"} found.`;
    return true;
  } catch (err) {
    ollamaModel.replaceChildren(new Option("Could not load models", ""));
    throw err;
  } finally {
    ollamaRefresh.disabled = false;
  }
}

async function loadLlmSettings() {
  const stored = await chrome.storage.local.get("llmSettings");
  llmSettings = { ...DEFAULT_LLM_SETTINGS, ...stored.llmSettings };
  providerSelect.value = llmSettings.provider;
  openaiApiKey.value = llmSettings.openaiApiKey;
  if (![...openaiModel.options].some((option) => option.value === llmSettings.openaiModel)) {
    openaiModel.add(new Option(`${llmSettings.openaiModel} (saved)`, llmSettings.openaiModel));
  }
  openaiModel.value = llmSettings.openaiModel;
  ollamaHost.value = llmSettings.ollamaHost;
  updateProviderFields();
  if (llmSettings.provider === "ollama" && llmSettings.ollamaHost) {
    try {
      await loadOllamaModels(llmSettings.ollamaModel);
    } catch (err) {
      settingsStatus.textContent = err.message;
    }
  }
}

settingsBtn.addEventListener("click", () => {
  const visible = settingsPanel.classList.toggle("visible");
  settingsBtn.setAttribute("aria-expanded", String(visible));
});

providerSelect.addEventListener("change", async () => {
  updateProviderFields();
  if (providerSelect.value === "ollama" && ollamaHost.value.trim()) {
    try {
      await loadOllamaModels(llmSettings.ollamaModel);
    } catch (err) {
      settingsStatus.textContent = err.message;
    }
  }
});

ollamaRefresh.addEventListener("click", async () => {
  try {
    await loadOllamaModels(ollamaModel.value || llmSettings.ollamaModel);
  } catch (err) {
    settingsStatus.textContent = err.message;
  }
});

ollamaHost.addEventListener("input", () => {
  ollamaModel.replaceChildren(new Option("Load models from Ollama", ""));
  ollamaModel.disabled = true;
});

ollamaHost.addEventListener("change", async () => {
  if (!ollamaHost.value.trim()) return;
  try {
    await loadOllamaModels();
  } catch (err) {
    settingsStatus.textContent = err.message;
  }
});

settingsSave.addEventListener("click", async () => {
  const next = {
    provider: providerSelect.value,
    openaiApiKey: openaiApiKey.value.trim(),
    openaiModel: openaiModel.value.trim(),
    ollamaHost: ollamaHost.value.trim(),
    ollamaModel: ollamaModel.value
  };
  if (next.provider === "openai" && (!next.openaiApiKey || !next.openaiModel)) {
    settingsStatus.textContent = "Enter an OpenAI API key and model.";
    return;
  }
  if (next.provider === "ollama") {
    try {
      next.ollamaHost = parseOllamaHost(next.ollamaHost);
    } catch (err) {
      settingsStatus.textContent = err.message;
      return;
    }
    if (!next.ollamaModel) {
      settingsStatus.textContent = "Load and select an available Ollama model.";
      return;
    }
  }
  llmSettings = next;
  await chrome.storage.local.set({ llmSettings });
  await detectContextWindow();
  settingsStatus.textContent = "Settings saved.";
  setTimeout(() => {
    settingsStatus.textContent = "Provider settings are stored locally in this browser profile.";
  }, 2000);
});

function switchToTab(panelTabName, ctx = currentContext) {
  if (!ctx) return;
  ctx.panelTab = panelTabName;
  for (const b of tabBtns) b.classList.toggle("active", b.dataset.tab === panelTabName);
  const isProcess = panelTabName === "process";
  processControls.style.display = isProcess ? "flex" : "none";
  outputArea.style.display = isProcess ? "flex" : "none";
  chatArea.style.display = isProcess ? "none" : "flex";
  chatArea.classList.toggle("visible", !isProcess);
  if (!isProcess) {
    if (!ctx.chatInitialized && ctx.articleText) initChat(ctx);
    if (!ctx.articleText) addChatMsg("system", "Load a page first, then switch to Ask tab.");
  }
}

for (const btn of tabBtns) {
  btn.addEventListener("click", () => switchToTab(btn.dataset.tab));
}

document.addEventListener("click", (e) => {
  const link = e.target.closest(".time-link");
  if (!link) return;
  e.preventDefault();
  const seconds = Number(link.dataset.seconds);
  if (Number.isFinite(seconds)) jumpToTime(seconds);
});

function isYouTubeUrl(url) {
  try {
    const u = new URL(url);
    const host = u.hostname.replace(/^www\./, "");
    if (host === "youtu.be") return true;
    if (host === "youtube.com" && u.pathname.startsWith("/watch")) return true;
    return false;
  } catch {
    return false;
  }
}

function ensureContentScripts(tabId) {
  return chrome.scripting
    .executeScript({
      target: { tabId },
      files: ["readability.js", "content-script.js"]
    })
    .catch(() => {});
}

async function sendMessageWithInjection(tabId, action) {
  try {
    return await chrome.tabs.sendMessage(tabId, { action });
  } catch (err) {
    if (/Receiving end does not exist|Could not establish connection/i.test(err.message)) {
      await ensureContentScripts(tabId);
      await new Promise((r) => setTimeout(r, 150));
      return await chrome.tabs.sendMessage(tabId, { action });
    }
    throw err;
  }
}

async function getPageContent(tab, ctx) {
  if (!tab) throw new Error("No active tab");
  ctx.url = tab.url || "";
  ctx.isYouTube = isYouTubeUrl(ctx.url);
  const isVisible = () => ctx === currentContext;

  if (ctx.isYouTube) {
    ctx.resultSource = "";
    if (isVisible()) {
      resultEl.innerHTML = "";
      copyBtn.style.display = "none";
    }
    try {
      const resp = await sendMessageWithInjection(tab.id, "extractYouTube");
      if (!resp?.success) throw new Error(resp?.error || "Could not extract YouTube video data.");
      ctx.currentVideoId = resp.videoId || "";
      ctx.articleTitle = resp.title || tab.title || "";
      ctx.transcript = resp.transcript || "";
      ctx.transcriptError = resp.transcriptError || "";
      const parts = [];
      if (resp.title) parts.push(`Title: ${resp.title}`);
      if (resp.description) parts.push(`Description:\n${resp.description}`);
      if (resp.transcript) parts.push(`Transcript:\n${resp.transcript}`);
      ctx.articleText = parts.join("\n\n");
      if (!resp.transcript && !resp.description) {
        throw new Error("No transcript or description could be extracted for this video.");
      }
    } catch (err) {
      throw new Error(`YouTube extraction failed: ${err.message}`);
    }
  } else {
    try {
      const resp = await sendMessageWithInjection(tab.id, "extractArticle");
      if (resp?.success && resp.article?.textContent) {
        ctx.articleText = resp.article.textContent;
        ctx.articleTitle = resp.article.title || tab.title || "";
      } else {
        throw new Error("No article returned");
      }
    } catch {
      const fallback = await chrome.scripting.executeScript({
        target: { tabId: tab.id },
        func: () => ({
          text: document.body?.innerText || "",
          title: document.title
        })
      });
      const r = fallback?.[0]?.result;
      ctx.articleText = r?.text || "";
      ctx.articleTitle = r?.title || tab.title || "";
    }
  }
  if (!ctx.articleText.trim()) throw new Error("No readable text found on this page.");
  ctx.detectedLang = detectLanguage(ctx.articleText);
  if (ctx.detectedLang) applyCJKFonts();
  if (ctx.isYouTube) {
    ctx.templateValue = "youtube_summary";
  } else {
    if (ctx.templateValue === "youtube_summary") ctx.templateValue = "summarise";
  }
  if (isVisible()) {
    pageTitleEl.textContent = ctx.articleTitle || ctx.tabTitle || "Untitled page";
    templateSelect.value = ctx.templateValue;
    updateTokenEstimate(ctx);
    renderTranscript(ctx);
  }
}

function updateTokenEstimate(ctx) {
  if (!ctx || !ctx.articleText) {
    tokenEstimateEl.textContent = "";
    return;
  }
  const chars = ctx.articleText.length;
  const estTokens = ctx.detectedLang ? Math.ceil(chars / 1.5) : Math.ceil(chars / 4);
  const chunks = Math.ceil(chars / getChunkChars(ctx));
  tokenEstimateEl.textContent = `~${estTokens.toLocaleString()} tokens${chunks > 1 ? ` (will chunk into ${chunks} parts)` : ""}`;
}

function renderTranscript(ctx) {
  if (!ctx || !ctx.isYouTube) {
    transcriptRow.style.display = "none";
    transcriptEl.style.display = "none";
    transcriptEl.innerHTML = "";
    return;
  }
  if (ctx.transcript) {
    transcriptToggle.innerHTML = `<span class="caret">${ctx.transcriptOpen ? "▾" : "▸"}</span>${ctx.transcriptOpen ? "Hide" : "Show"} transcript`;
    if (ctx.transcriptOpen) {
      transcriptEl.style.display = "block";
      transcriptEl.innerHTML = renderMarkdown(ctx.transcript);
    } else {
      transcriptEl.style.display = "none";
    }
  } else if (ctx.transcriptError) {
    transcriptToggle.innerHTML = `<span class="caret">▸</span>Show transcript`;
    transcriptEl.style.display = "block";
    transcriptEl.innerHTML = `<p class="transcript-error">${escapeHtml(ctx.transcriptError)}</p>`;
  } else {
    transcriptRow.style.display = "none";
    transcriptEl.style.display = "none";
    transcriptEl.innerHTML = "";
  }
  transcriptRow.style.display = ctx.transcript || ctx.transcriptError ? "flex" : "none";
  transcriptCopy.style.display = ctx.transcriptOpen ? "block" : "none";
}

transcriptToggle.addEventListener("click", () => {
  const ctx = currentContext;
  if (!ctx) return;
  ctx.transcriptOpen = !ctx.transcriptOpen;
  renderTranscript(ctx);
});

transcriptCopy.addEventListener("click", async () => {
  const ctx = currentContext;
  if (!ctx || !ctx.transcript) return;
  try {
    await navigator.clipboard.writeText(ctx.transcript);
    transcriptCopy.textContent = "Copied!";
    setTimeout(() => { transcriptCopy.textContent = "Copy"; }, 2000);
  } catch {
    transcriptCopy.textContent = "Failed";
  }
});

function detectLanguage(text) {
  if (!text) return null;
  const cjk = (text.match(/[\u4E00-\u9FFF\u3400-\u4DBF\uF900-\uFAFF]/g) || []).length;
  const hiragana = (text.match(/[\u3040-\u309F]/g) || []).length;
  const katakana = (text.match(/[\u30A0-\u30FF]/g) || []).length;
  const total = text.replace(/\s/g, "").length;
  if (total === 0) return null;
  if (cjk / total > 0.2) {
    return hiragana + katakana > 5 ? "ja" : "zh-TW";
  }
  return null;
}

function applyCJKFonts() {
  let style = document.getElementById("cjk-fonts");
  if (!style) {
    style = document.createElement("style");
    style.id = "cjk-fonts";
    document.head.appendChild(style);
  }
  style.textContent = `
    body, #result, .msg.assistant {
      font-family: "PingFang TC", "Noto Sans TC", "Microsoft JhengHei", "Hiragino Mincho ProN", "Yu Mincho", -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
    }
  `;
}

function getLangInstruction(ctx) {
  if (ctx.detectedLang) {
    return " Please write your entire response in Traditional Chinese.";
  }
  return "";
}

function getChunkChars(ctx) {
  return ctx.detectedLang ? chunkCfg.cjk : chunkCfg.latin;
}

async function detectContextWindow() {
  Object.assign(chunkCfg, DEFAULT_CHUNK_CFG);
  if (llmSettings.provider === "openai") {
    const budget = Math.floor(OPENAI_CONTEXT_TOKENS * 0.35);
    chunkCfg.latin = budget * 4;
    chunkCfg.cjk = budget;
    chunkCfg.group = 4;
    return;
  }
  try {
    const isOllama = llmSettings.provider === "ollama";
    const base = isOllama ? llmSettings.ollamaHost : APFEL_API_URL.replace(/\/v1\/chat\/completions$/, "");
    const model = isOllama ? llmSettings.ollamaModel : APFEL_MODEL;
    let ctx = null;
    try {
      const resp = await fetch(`${base}/v1/models`);
      if (resp.ok) {
        const data = await resp.json();
        const models = data.data || [];
        const entry = models.find((m) => m.id === model) || models[0];
        if (entry) {
          ctx = entry.context_length ?? entry.max_context_length ?? entry.context;
        }
        if (!ctx) ctx = data.context_length ?? data.max_context_length;
      }
    } catch {}
    if (!ctx) {
      try {
        const resp = await fetch(`${base}/api/show`, {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ model })
        });
        if (resp.ok) {
          const data = await resp.json();
          ctx = data.model_info?.["general.context_length"];
        }
      } catch {}
    }
    if (typeof ctx === "number" && ctx >= 4096) {
      const budget = Math.floor(ctx * 0.35);
      chunkCfg.latin = Math.max(4000, Math.min(16000, Math.floor(budget * 4)));
      chunkCfg.cjk = Math.max(1200, Math.min(6000, budget));
      chunkCfg.group = Math.max(2, Math.min(4, Math.floor(budget / 1000)));
    }
  } catch {}
}

function chunkText(text, ctx) {
  const limit = getChunkChars(ctx);
  if (text.length <= limit) return [text];
  const chunks = [];
  const sentences = text.match(/[^.!?\n]+[.!?\n]*/g) || [text];
  let cur = "";
  for (const s of sentences) {
    if ((cur + s).length > limit && cur) {
      chunks.push(cur.trim());
      cur = s;
    } else {
      cur += s;
    }
  }
  if (cur.trim()) chunks.push(cur.trim());
  return chunks;
}

function setStatus(msg, isError) {
  statusEl.textContent = msg;
  statusEl.className = isError ? "error" : "";
}

async function streamCompletion(messages, onToken) {
  const isOpenAI = llmSettings.provider === "openai";
  const isOllama = llmSettings.provider === "ollama";
  if (isOpenAI && (!llmSettings.openaiApiKey || !llmSettings.openaiModel)) {
    throw new Error("Open LLM settings and enter an OpenAI API key and model.");
  }
  if (isOllama && (!llmSettings.ollamaHost || !llmSettings.ollamaModel)) {
    throw new Error("Open LLM settings and configure an Ollama host and model.");
  }
  const headers = { "Content-Type": "application/json" };
  if (isOpenAI) headers.Authorization = `Bearer ${llmSettings.openaiApiKey}`;
  const body = {
    model: isOpenAI ? llmSettings.openaiModel : isOllama ? llmSettings.ollamaModel : APFEL_MODEL,
    stream: true,
    messages
  };
  if (isOllama) body.options = { temperature: 0.2 };
  else if (!isOpenAI) body.temperature = 0.2;

  const apiUrl = isOpenAI ? OPENAI_API_URL : isOllama ? `${llmSettings.ollamaHost}/api/chat` : APFEL_API_URL;
  const controller = isOllama ? new AbortController() : null;
  const responseTimeout = controller ? setTimeout(() => controller.abort(), 60000) : null;
  let response;
  try {
    response = await fetch(apiUrl, {
      method: "POST",
      headers,
      body: JSON.stringify(body),
      signal: controller?.signal
    });
  } catch (err) {
    if (isOllama && err.name === "AbortError") {
      throw new Error(`Ollama model ${llmSettings.ollamaModel} did not start responding within 60 seconds. Check or restart the model on the Ollama server.`);
    }
    throw err;
  } finally {
    if (responseTimeout) clearTimeout(responseTimeout);
  }
  if (!response.ok) {
    const errBody = await response.text();
    let detail = errBody;
    try {
      const parsed = JSON.parse(errBody);
      detail = parsed.error?.message || parsed.error || errBody;
    } catch {}
    if (isOllama && response.status === 403) {
      detail = `Ollama rejected this extension's origin. Set OLLAMA_ORIGINS=chrome-extension://* on the Ollama server and restart it.`;
    }
    throw new Error(`API error (${response.status}): ${detail}`);
  }
  const reader = response.body.getReader();
  const decoder = new TextDecoder();
  let buffer = "";
  let full = "";
  while (true) {
    const { done, value } = await reader.read();
    if (done) break;
    buffer += decoder.decode(value, { stream: true });
    const lines = buffer.split("\n");
    buffer = lines.pop() || "";
    for (const line of lines) {
      const data = isOllama ? line.trim() : line.startsWith("data: ") ? line.slice(6).trim() : "";
      if (!data) continue;
      if (data === "[DONE]") continue;
      try {
        const parsed = JSON.parse(data);
        const delta = isOllama ? parsed.message?.content || "" : parsed.choices?.[0]?.delta?.content || "";
        if (delta) {
          full += delta;
          if (onToken) onToken(delta);
        }
      } catch {}
    }
  }
  return full;
}

function resolveTemplate(tmpl, text) {
  return {
    system: typeof tmpl.system === "function" ? tmpl.system(text) : tmpl.system,
    user: typeof tmpl.user === "function" ? tmpl.user(text) : tmpl.user
  };
}

function makeOnResultToken(ctx) {
  return (t) => {
    ctx.resultSource += t;
    if (ctx === currentContext) {
      resultEl.innerHTML = renderMarkdown(ctx.resultSource);
      resultEl.scrollTop = resultEl.scrollHeight;
    }
  };
}

async function combineSummaries(parts, combinePrompt, langInstruction, ctx, finalOnToken) {
  let current = parts;
  while (current.length > 1) {
    const isFinalPass = current.length <= chunkCfg.group;
    const groups = [];
    for (let i = 0; i < current.length; i += chunkCfg.group) {
      const group = current.slice(i, i + chunkCfg.group);
      if (group.length === 1) {
        groups.push(group[0]);
        continue;
      }
      setStatus(processingQuip());
      const combined = await streamCompletion(
        [
          { role: "system", content: combinePrompt + langInstruction },
          {
            role: "user",
            content: `Combine these partial results:\n\n${group.map((s, j) => `Part ${j + 1}:\n${s}`).join("\n\n")}`
          }
        ],
        isFinalPass ? finalOnToken : () => {}
      );
      groups.push(combined);
    }
    current = groups;
  }
}

async function runTemplate(tmpl, text, langInstruction, ctx) {
  const chunks = chunkText(text, ctx);

  const getMessages = (txt) => {
    const { system, user } = resolveTemplate(tmpl, txt);
    return [
      { role: "system", content: system + langInstruction },
      { role: "user", content: user }
    ];
  };

  if (chunks.length === 1) {
    setStatus(processingQuip());
    ctx.resultSource = "";
    if (ctx === currentContext) resultEl.innerHTML = "";
    await streamCompletion(getMessages(text), makeOnResultToken(ctx));
    return;
  }

  const parts = [];
  for (let i = 0; i < chunks.length; i++) {
    setStatus(`Part ${i + 1} of ${chunks.length} — ${processingQuip()}`);
    parts.push(await streamCompletion(getMessages(chunks[i]), () => {}));
  }

  setStatus(processingQuip());
  ctx.resultSource = "";
  if (ctx === currentContext) resultEl.innerHTML = "";
  await combineSummaries(parts, tmpl.combine, langInstruction, ctx, makeOnResultToken(ctx));
}

async function processTemplate(text, templateKey, ctx) {
  const tmpl = TEMPLATES[templateKey];
  if (!tmpl) throw new Error("Unknown template");
  setSelectionNote(ctx, "", "");
  await runTemplate(tmpl, text, getLangInstruction(ctx), ctx);
}

function renderSelectionNote(ctx) {
  const note = $("selection-note");
  if (!note) return;
  if (!ctx.selectionNote) {
    note.style.display = "none";
    return;
  }
  const label =
    ctx.selectionMode && SELECTION_TEMPLATES[ctx.selectionMode]
      ? SELECTION_TEMPLATES[ctx.selectionMode].name
      : "";
  const preview =
    ctx.selectionNote.length > 400 ? ctx.selectionNote.slice(0, 400) + "…" : ctx.selectionNote;
  note.innerHTML = `<strong>${label}</strong>: ${escapeHtml(preview)}`;
  note.style.display = "block";
}

function setSelectionNote(ctx, text, mode) {
  ctx.selectionNote = text || "";
  ctx.selectionMode = mode || "";
  renderSelectionNote(ctx);
}

async function processSelectionMessage(data, ctx) {
  const tmpl = SELECTION_TEMPLATES[data.mode];
  if (!tmpl) throw new Error("Unknown action");
  switchToTab("process", ctx);
  setSelectionNote(ctx, data.text, data.mode);
  ctx.resultSource = "";
  resultEl.innerHTML = "";
  copyBtn.style.display = "none";
  setStatus(`${tmpl.name}ing highlighted text…`);
  await runTemplate(tmpl, data.text, selectionLangInstruction(data.text, data.mode), ctx);
  setStatus("Done");
  if (ctx === currentContext) copyBtn.style.display = "block";
}

processBtn.addEventListener("click", async () => {
  if (isProcessing || !currentContext) return;
  isProcessing = true;
  processBtn.disabled = true;
  const ctx = currentContext;
  ctx.resultSource = "";
  resultEl.innerHTML = "";
  setSelectionNote(ctx, "", "");
  copyBtn.style.display = "none";
  try {
    setStatus("Reading page...");
    const tab = await chrome.tabs.get(ctx.tabId).catch(() => null);
    if (!tab) throw new Error("No active tab");
    await getPageContent(tab, ctx);
    const template = ctx.templateValue || templateSelect.value;
    setStatus(`Using "${TEMPLATES[template].name}" template...`);
    await processTemplate(ctx.articleText, template, ctx);
    if (ctx === currentContext) copyBtn.style.display = "block";
  } catch (err) {
    setStatus(err.message, true);
    ctx.resultSource = "";
    if (ctx === currentContext) resultEl.innerHTML = "";
  } finally {
    isProcessing = false;
    processBtn.disabled = false;
  }
});

copyBtn.addEventListener("click", async () => {
  const ctx = currentContext;
  if (!ctx || !ctx.resultSource) return;
  try {
    await navigator.clipboard.writeText(ctx.resultSource);
    copyBtn.textContent = "Copied!";
    setTimeout(() => { copyBtn.textContent = "Copy"; }, 2000);
  } catch {
    copyBtn.textContent = "Failed";
  }
});

function addChatMsg(role, content, isMarkdown) {
  const div = document.createElement("div");
  div.className = `msg ${role}`;
  if (isMarkdown) {
    div.innerHTML = renderMarkdown(content);
  } else {
    div.textContent = content;
  }
  chatMessages.appendChild(div);
  chatMessages.scrollTop = chatMessages.scrollHeight;
}

function renderChatFor(ctx) {
  chatMessages.innerHTML = "";
  if (!ctx.chatInitialized) return;
  addChatMsg("system", `Chatting about: ${ctx.articleTitle || "current page"}`);
  addChatMsg(
    "assistant",
    "Ask me anything about this page. I'll answer based on its content."
  );
  for (const m of ctx.chatHistory) {
    addChatMsg(m.role, m.content, m.role === "assistant");
  }
}

function initChat(ctx) {
  ctx.chatInitialized = true;
  ctx.chatHistory = [];
  renderChatFor(ctx);
}

async function sendChatMessage() {
  const ctx = currentContext;
  if (!ctx) return;
  const question = chatInput.value.trim();
  if (!question || isProcessing) return;
  chatInput.value = "";
  isProcessing = true;
  chatSend.disabled = true;

  if (!ctx.chatInitialized) {
    try {
      if (!ctx.articleText) {
        const tab = await chrome.tabs.get(ctx.tabId).catch(() => null);
        if (!tab) throw new Error("No active tab");
        await getPageContent(tab, ctx);
      }
      initChat(ctx);
    } catch (err) {
      if (ctx === currentContext) addChatMsg("assistant", `Error: ${err.message}`);
      isProcessing = false;
      chatSend.disabled = false;
      return;
    }
  }

  if (ctx === currentContext) addChatMsg("user", question);

  const qLang = detectLanguage(question);
  if (qLang && !ctx.detectedLang) {
    ctx.detectedLang = qLang;
    applyCJKFonts();
  }

  const systemMsg = {
    role: "system",
    content: `You are a helpful assistant answering questions about the following webpage. Use only the provided content to answer. If the answer is not in the content, say so.\n\nTitle: ${ctx.articleTitle}\n\nContent:\n${ctx.articleText.substring(0, getChunkChars(ctx))}` + getLangInstruction(ctx)
  };

  const userMsg = { role: "user", content: question };
  ctx.chatHistory.push(userMsg);

  const aiDiv = document.createElement("div");
  aiDiv.className = "msg assistant";
  if (ctx === currentContext) {
    chatMessages.appendChild(aiDiv);
    chatMessages.scrollTop = chatMessages.scrollHeight;
  }

  let full = "";
  try {
    const msgs = [systemMsg, ...ctx.chatHistory.slice(-20)];
    await streamCompletion(msgs, (t) => {
      full += t;
      if (ctx === currentContext) {
        aiDiv.innerHTML = renderMarkdown(full);
        chatMessages.scrollTop = chatMessages.scrollHeight;
      }
    });
  } catch (err) {
    if (ctx === currentContext) aiDiv.innerHTML = renderMarkdown(`Error: ${err.message}`);
  }

  ctx.chatHistory.push({ role: "assistant", content: full });
  isProcessing = false;
  chatSend.disabled = false;
  if (ctx === currentContext) chatInput.focus();
}

chatSend.addEventListener("click", sendChatMessage);
chatInput.addEventListener("keydown", (e) => {
  if (e.key === "Enter" && !e.shiftKey) {
    e.preventDefault();
    sendChatMessage();
  }
});

function renderContext(ctx) {
  pageTitleEl.textContent = ctx.articleTitle || ctx.tabTitle || "Untitled page";
  templateSelect.value = ctx.templateValue || "summarise";
  updateTokenEstimate(ctx);
  resultEl.innerHTML = ctx.resultSource ? renderMarkdown(ctx.resultSource) : "";
  copyBtn.style.display = ctx.resultSource ? "block" : "none";
  renderSelectionNote(ctx);
  renderTranscript(ctx);
  renderChatFor(ctx);
  switchToTab(ctx.panelTab || "process", ctx);
  if (ctx.detectedLang) applyCJKFonts();
}

async function autoLoadContext(tab, ctx) {
  setStatus("Reading page...");
  try {
    await getPageContent(tab, ctx);
    setStatus("");
  } catch {
    if (ctx === currentContext) setStatus("");
    ctx.url = "";
  }
}

function saveCurrentContext() {
  if (currentContext && currentContext.tabId) {
    contexts.set(currentContext.tabId, currentContext);
  }
}

async function loadContextForTab(tab) {
  if (!tab) return;
  saveCurrentContext();
  let ctx = contexts.get(tab.id);
  if (!ctx || (ctx.url && tab.url && ctx.url !== tab.url)) {
    ctx = makeContext(tab);
    contexts.set(tab.id, ctx);
  }
  ctx.url = tab.url || ctx.url;
  ctx.tabTitle = tab.title || ctx.tabTitle;
  currentContext = ctx;
  currentTabId = tab.id;
  renderContext(ctx);
  if (!ctx.articleText) {
    await autoLoadContext(tab, ctx);
  }
}

async function getActiveTab() {
  const [tab] = await chrome.tabs.query({ active: true, currentWindow: true });
  return tab || null;
}

async function loadActiveTab() {
  const tab = await getActiveTab();
  if (!tab) return;
  if (tab.id === currentTabId && contexts.get(tab.id) === currentContext) return;
  await loadContextForTab(tab);
}

chrome.tabs.onActivated.addListener(async () => {
  try {
    const tab = await getActiveTab();
    if (!tab || tab.id === currentTabId) return;
    await loadContextForTab(tab);
  } catch {}
});

chrome.tabs.onUpdated.addListener(async (tabId, changeInfo, tab) => {
  try {
    if (changeInfo.status !== "complete") return;
    const existing = contexts.get(tabId);
    const freshUrl = (tab && tab.url) || "";
    if (existing && freshUrl && existing.url === freshUrl) return;
    contexts.delete(tabId);
    if (tabId === currentTabId) await loadActiveTab();
  } catch {}
});

chrome.tabs.onRemoved.addListener((tabId) => {
  contexts.delete(tabId);
  if (tabId === currentTabId) {
    currentContext = null;
    currentTabId = null;
    loadActiveTab().catch(() => {});
  }
});

chrome.windows.onFocusChanged.addListener(async () => {
  try {
    await loadActiveTab();
  } catch {}
});

templateSelect.addEventListener("change", () => {
  if (currentContext) currentContext.templateValue = templateSelect.value;
});

async function handlePendingSelection() {
  const { pendingSelection } = await chrome.storage.local.get("pendingSelection");
  if (!pendingSelection) return;
  await chrome.storage.local.remove("pendingSelection");
  if (isProcessing || !pendingSelection.text) return;
  try {
    let tab = await getActiveTab();
    if (pendingSelection.tabId && tab && pendingSelection.tabId !== tab.id) {
      tab = await chrome.tabs.get(pendingSelection.tabId).catch(() => null);
    }
    if (!tab) return;
    await loadContextForTab(tab);
    if (currentContext) {
      await processSelectionMessage(pendingSelection, currentContext);
    }
  } catch (err) {
    setStatus(err.message, true);
  }
}

chrome.storage.onChanged.addListener((changes, area) => {
  if (area === "local" && changes.pendingSelection) handlePendingSelection();
});

async function initialize() {
  await loadLlmSettings();
  await detectContextWindow();
  await loadActiveTab();
  await handlePendingSelection();
}

initialize().catch((err) => setStatus(err.message, true));
